rules:
  exclude_new_customer:
    enabled: false
    table: "features.bank_ph_features"
    key: "cifno"
    params:
      min_vint_months: 3
  segment_rule:
    enabled: false
    table: "clean.cif_flag_mapping"
    key: "cifno"
    params:
      exclude_non_active: true   # bank_active_flag == 0
      exclude_existing_axa: true # axa_pol_flag == 1
  min_balance_rule:
    enabled: false
    table: "features.balance_features"
    key: "cifno"
    params:
      min_avgd: 1000000 # Example: 1 Million IDR